[package]
name = "onionsalt"
version = "0.1.0"
authors = ["David Roundy <roundyd@physics.oregonstate.edu>"]

[dependencies]
rand = "0.3" # Or a specific version

arrayref = { version = "0.1.0", git = "https://github.com/droundy/arrayref" }

[dev-dependencies]
quickcheck = "*"
