[package]
name = "onionsalt"
version = "0.1.0"
authors = ["David Roundy <roundyd@physics.oregonstate.edu>"]

[dependencies]
rand = "0.3" # Or a specific version

arrayref = "0.2"

[dev-dependencies]
quickcheck = "*"
